export const USER_ACTION_TYPES = {
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    CREATE_EMAIL_USER_ACCOUNT_START: 'CREATE_EMAIL_USER_ACCOUNT_START',
    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'SIGNIN_FAILURE',
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNOUT_START: 'SIGNOUT_START',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
    CLEAR_USER_ERROR: 'CLEAR_USER_ERROR'
}